version: '3.8'

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_CONVEX_URL=${VITE_CONVEX_URL}
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - NPM_CONFIG_PYTHON=/usr/bin/python3
    ports:
      - '${PORT:-3000}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ai-town-network

  dashboard:
    image: ghcr.io/get-convex/convex-dashboard:latest
    ports:
      - '${DASHBOARD_PORT:-6791}:6791'
    environment:
      - NEXT_PUBLIC_DEPLOYMENT_URL=http://convex:3210
    depends_on:
      convex:
        condition: service_healthy
    networks:
      - ai-town-network

volumes:
  convex_data:

networks:
  ai-town-network:
    driver: bridge
